# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

bt_style = ("QPushButton {background-color: rgb(51,122,183); color: White; border-radius: 24px;}"
                           "QPushButton:pressed {background-color:rgb(31,101,163) ; }")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(0, 320, 150, 90))
        self.btn_zero.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_zero.setObjectName("btn_zero")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(0, 0, 380, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Hebrew")
        font.setPointSize(15)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgb(94, 92, 100);\n"
"color: rgb(255, 255, 255);")
        self.label_result.setObjectName("label")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(150, 320, 150, 90))
        self.btn_equal.setStyleSheet("background-color: rgb(181, 131, 190);")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 230, 100, 90))
        # self.btn_7.setStyleSheet("background-color: rgb(181, 131, 90); border-radius: 24px;")
        self.btn_7.setStyleSheet(bt_style)

        self.btn_7.setObjectName("btn_7")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 140, 100, 90))
        self.btn_4.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_4.setObjectName("btn_4")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 50, 100, 90))
        self.btn_1.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 50, 100, 90))
        self.btn_2.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_2.setObjectName("btn_2")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(100, 140, 100, 90))
        self.btn_5.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_5.setObjectName("btn_5")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 230, 100, 90))
        self.btn_8.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_8.setObjectName("btn_8")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(200, 50, 100, 90))
        self.btn_3.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_3.setObjectName("btn_3")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(200, 140, 100, 90))
        self.btn_6.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_6.setObjectName("btn_6")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(200, 230, 100, 90))
        self.btn_9.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_9.setObjectName("btn_9")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(300, 50, 80, 90))
        self.btn_plus.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_plus.setObjectName("btn_10")
        self.btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_minus.setGeometry(QtCore.QRect(300, 140, 80, 90))
        self.btn_minus.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_minus.setObjectName("btn_11")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(300, 230, 80, 90))
        self.btn_mult.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_mult.setObjectName("btn_12")
        self.btn_devide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_devide.setGeometry(QtCore.QRect(300, 320, 80, 90))
        self.btn_devide.setStyleSheet("background-color: rgb(181, 131, 90);")
        self.btn_devide.setObjectName("btn_13")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.label_result.setText(_translate("MainWindow", "0"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_devide.setText(_translate("MainWindow", "/"))

    def add_function(self):
        self.btn_zero.clicked.connect(lambda: self.write_number(self.btn_zero.text()))
        # self.btn_equal.clicked.connect(lambda: self.write_number(self.btn_equal.text()))
        self.btn_1.clicked.connect(lambda: self.write_number(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.write_number(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.write_number(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.write_number(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.write_number(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.write_number(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.write_number(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.write_number(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.write_number(self.btn_9.text()))
        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_minus.clicked.connect(lambda: self.write_number(self.btn_minus.text()))
        self.btn_mult.clicked.connect(lambda: self.write_number(self.btn_mult.text()))
        self.btn_devide.clicked.connect(lambda: self.write_number(self.btn_devide.text()))

        self.btn_equal.clicked.connect(self.result)
    
    def write_number(self, number):
        if self.label_result.text() == "0" or self.is_equal:
            self.label_result.setText(number)
            self.is_equal = False
        else:
            self.label_result.setText(self.label_result.text() + number)

    def result(self):
        res = eval(self.label_result.text())
        self.label_result.setText("Результат: " + str(res))
        self.is_equal = True

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
